### ISSUE TITLE
The website style needs fix

### ISSUE THREAD

**Issue by astonzhang** [d2l-ai/d2l-tr#33]
On tr.d2l.ai, if you scroll up and down, you'll notice issues on the homepage including extra top margins and grey banner:
![Screen Shot 2021-12-15 at 12 53 17 PM](https://user-images.githubusercontent.com/22279212/146263466-f230944b-8494-4209-980a-07a88e5cb05d.png)

Likely causes would be some undesirable changes to static/frontpage/frontpage.html, style files, or lib dependencies.

@AnirudhDagar Can you take a look? Thanks.

**Comment by semercim** [comment]
Hi,

I have already fixed it and  committed to the master branch.
@AnirudhDagar, could you merge the master to the release please?

Thanks,

**Comment by astonzhang** [comment]
Thanks! 
Will merge it after https://github.com/d2l-ai/d2l-tr/pull/34 passes CI

**Comment by astonzhang** [comment]
Yes, it's fixed:
http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-tr/master/
