### ISSUE TITLE
pdf links in the header of the Turkish version are broken.

### ISSUE THREAD

**Issue by semercim** [d2l-ai/d2l-tr#35]
Even though the pdfs are created by CI pipeline, they are not reachable from the website.

**Comment by AnirudhDagar** [comment]
@astonzhang should we make a new release with [this](https://github.com/d2l-ai/d2l-tr/commit/6402f9ddacf1556c75bb756b6d599904abc77040) fix? The release version is still broken.

**Comment by astonzhang** [comment]
Sure. Please send a PR to merge master to release. If it looks good to you, merge it (by creating a merge commit).
